-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="step",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d hrs %d min',
    hour_format='%d hrs',

    welcome_use="Hello, I am your Mi Band.",
    last_week_walked_format='Last week, you walked %d steps.',
    last_week_walked_info_format='Walked %d km, burned %d cal.',
    last_month_walked_format='Last month, you walked %d steps.',
    last_month_walked_info_format='Walked %d km, burned %d cal.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Find out more to do with Mi Band.",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Mi Band will track your activities and help you to be healthier.",
    unlock_hint="Unlock phone with your Mi Band",
    unlock_hint_info="say Goodbye to the old times.",
    no_data_hint_0="Keep moving, make sports a part of your life.",
    no_data_hint_1="Want to stay happy? Just run.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="You haven’t linked any Mi Band to this account, please link one now. ",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="New record, %d steps, %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d min",
    active_time_format_1="%d hr",
    active_time_format_2="%d hr %d min",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format=", a total of %d m.",
    activity_walk_format="%s Walked %d steps %s",
    activity_walk_consumed_format="Burned %d cal %s",

    activity_activity_format="%s %s work out %s",
    last_night_sleeped_good_format="Last night, you slept for %s. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %s.",
    deep_sleep_format="Deep sleep stage was %s.",

    battery_low_info="Low in battery, please charge your Mi Band.",
    battery_very_low_info="Connect to power",

    cannot_find_bracelet="Unable to find your Mi Band?",
    cannot_find_bracelet_info="Please make sure your Mi Band has power and stays nearby your phone.",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="New record!",
 }

 localization_Croatian_table = {
	calories_table={
	    {str="≈1 dva kuhana jaja",	calories=96},
        {str="≈1 kriška kruha",	calories=100},
        {str="≈1 limenka ledenog čaja",	calories=112},
        {str="≈1 omlet",	calories=118},
        {str="≈2 ražnjića",	calories=124},
        {str="≈1 limenka Coca-Cole",	calories=153},
        {str="≈3 ražnjića",	calories=186},
        {str="≈2 dva tvrdo kuhana jaja",	calories=192},
        {str="≈2 kriške kruha",	calories=200},
        {str="≈1 zdjelica riže",	calories=210},
        {str="≈1 kruh",	calories=221},
        {str="≈1 paket slatkiša",	calories=223},
        {str="≈2 limenke ledenog čaja",	calories=224},
        {str="≈1 mali krumpir",	calories=224},
        {str="≈1 kolač",	calories=224},
        {str="≈2 omleta",	calories=236},
        {str="≈4 ražnjića",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 krafna",	calories=270},
        {str="≈1 burek s mesom",	calories=272},
        {str="≈3 tvrdo kuhana jaja",	calories=288},
        {str="≈1 konus",	calories=290},
        {str="≈3 kriške kruha",	calories=300},
        {str="≈2 limenke Coca-Cole",	calories=306},
        {str="≈1 mali pomfrit",	calories=328},
        {str="≈3 omeleta",	calories=354},
        {str="≈1 kolač s jajima",	calories=375},
        {str="≈4 kriške kruha",	calories=400},
        {str="≈1 veliki pomfrit",	calories=402},
        {str="≈2 zdjelice riže",	calories=420},
        {str="≈2 kruha",	calories=442},
        {str="≈2 paketa ušećerenog korijena",	calories=446},
        {str="≈2 pite",	calories=448},
        {str="≈1 paket instant rezanaca",	calories=470},
        {str="≈5 kriški kruha",	calories=500},
        {str="≈1 tanjur pržene riže",	calories=516},
        {str="≈2 hamburgera",	calories=520},
        {str="≈2 krafne",	calories=540},
        {str="≈2 bureka s mesom",	calories=544},
        {str="≈2 konusa",	calories=580},
        {str="≈1 zdjelica instant rezanaca",	calories=581},
        {str="≈1 zdjelica goveđih rezanaca",	calories=593},
        {str="≈10 ražnjića",	calories=620},
        {str="≈3 zdjelice riže",	calories=630},
        {str="≈3 kruha",	calories=663},
        {str="≈2 tarta od jaja",	calories=750},
        {str="≈3 krafne",	calories=810},
        {str="≈3 bureka s mesom",	calories=816},
	},
	
	ok='U redu',
	
	hour='sati',
	minute='min',
	month='mjesec',
	day='dan',
	step="korak",
	km='KM',
	minute_format='%d min',
	hour_minute_format='%d sati %d min',
	hour_format='%d sati',
	
	welcome_use="Pozdrav, Ja sam tvoj Mi Band.",
	last_week_walked_format='Prošli tjedan, prohodali ste %d koraka.',
	last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
	last_month_walked_format='Prošli mjesec, prohodali ste %d koraka.',
	last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',
	
	get_over_format=", O %d grama ili masti.",
	click_to_get_help="Saznajte što sve možete s Mi Band.",
	take_a_walk="Prošetajte s Mi Band.",
	take_a_walk_info="Mi Band će pratiti vaše aktivnosti i pomoći vam da se osjećate zdravije.",
	unlock_hint="Otključajte telefon vašim Mi Band,",
	unlock_hint_info="recite \"Zbogom\" starim vremenima.",
	no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
	no_data_hint_1="Želite ostati sretni? Samo trčite.",
	no_data_hint_2="Kardio vježba će vam omogućiti da se osjećate laganije i svježe svaki dan! ",
	no_data_hint_3="Normalna odrasla troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
	not_binded_hint="Nijedan Mi Band nije povezan na ovaj račun, povežite jedan sada. ",
	new_record_info="WoW! Oborili ste rekord u hodanju.",
	new_record_format="Novi rekord, %d koraka, %s %d",
	today_goal_reached="Čestitke! Postigli ste danjašnji cilj. ",
	week_continue_reach_goal="Postigli ste cilj svakog dana ovog tjedna! Stvarno fantastičan tjedan!",
	challenge_format="Postigli ste svoj cilj za %d dan(a)!",
	personal_best_format="Vaš najveći rekord je %d dan(a)!",
	active_time_format_0="%d sati",
	active_time_format_1="%d sati",
	active_time_format_2="%d sati %d min",
	activie_run_format_0="Trčano %s. Dobro je!",
	activie_run_format_1="Trčano %s. Ide vam fantastično!",
	activie_run_format_2="Trčano %s, Nevjerojatno ste izdržljivi!",
	activie_run_consumed="Potrošeno %d kal. %s",
	
	get_distance_format=", ukupno od %d m.",
	activity_walk_format="%s Prohodano %d koraka %s",
	activity_walk_consumed_format="Potrošeno %d kal %s",
	
	activity_activity_format="%s Napravljeno %s %s",
	last_night_sleeped_good_format="Prošle noći ste spavali %d sati %d min. Sad ste stvarno naspavani!",
	last_night_sleeped_normal_format="Prošle noći ste spavali %d sati %d min.",
	deep_sleep_format="Faza dubokog sna je bila %d sati %d min.",
	
	battery_low_info="Slaba baterija, stavite Mi Band na punjenje.",
	battery_very_low_info="Priključite na punjač",
	
	cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
	cannot_find_bracelet_info="Uvjerite se da vaš MiBand ima energije i nalazi se u blizini vašeg telefona.",
	
	challenge_to_get="%s dana od postizanja novog rekorda!",
	record_reach_max="Postigli ste svoj najveći novi rekord!",
	new_record_born="Novi rekord!",
 }