-------------------------
-- Croatian Localization String resources
-- adria.mobiledevs.net (2014)
-- MASVA
-------------------------
localization_Croatian_table = {
    calories_table={
         {str=" ",	calories=96},
         {str=" ",	calories=100},
         {str=" ",	calories=112},
         {str=" ",	calories=118},
         {str=" ",	calories=124},
         {str=" ",	calories=153},
         {str=" ",	calories=186},
         {str=" ",	calories=192},
         {str=" ",	calories=200},
         {str=" ",	calories=210},
         {str=" ",	calories=221},
         {str=" ",	calories=223},
         {str=" ",	calories=224},
         {str=" ",	calories=224},
         {str=" ",	calories=224},
         {str=" ",	calories=236},
         {str=" ",	calories=248},
         {str=" ",	calories=260},
         {str=" ",	calories=270},
         {str=" ",	calories=272},
         {str=" ",	calories=288},
         {str=" ",	calories=290},
         {str=" ",	calories=300},
         {str=" ",	calories=306},
         {str=" ",	calories=328},
         {str=" ",	calories=354},
         {str=" ",	calories=375},
         {str=" ",	calories=400},
         {str=" ",	calories=402},
         {str=" ",	calories=420},
         {str=" ",	calories=442},
         {str=" ",	calories=446},
         {str=" ",	calories=448},
         {str=" ",	calories=470},
         {str=" ",	calories=500},
         {str=" ",	calories=516},
         {str=" ",	calories=520},
         {str=" ",	calories=540},
         {str=" ",	calories=544},
         {str=" ",	calories=580},
         {str=" ",	calories=581},
         {str=" ",	calories=593},
         {str=" ",	calories=620},
         {str=" ",	calories=630},
         {str=" ",	calories=663},
         {str=" ",	calories=750},
         {str=" ",	calories=810},
         {str=" ",	calories=816},
    },

    ok='U redu',

    hour='sati',
    minute='min',
    month='mjesec',
    day='dan',
    step="korak",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%ds %d m',
    hour_format='%ds',

    welcome_use="Dobrodošli...",
    last_week_walked_format='Prošli tjedan, prohodali ste %d koraka.',
    last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
    last_month_walked_format='Prošli mjesec, prohodali ste %d koraka.',
    last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',

    get_over_format=", oko %d grama ili masti.",
    click_to_get_help="Saznajte što sve možete s Mi Band.",
    take_a_walk="Prošetajte s Mi Band.",
    take_a_walk_info="Mi Band će pratiti vaše aktivnosti i pomoći vam da se osjećate zdravije.",
    unlock_hint="Otključajte telefon vašim Mi Bandom,",
    unlock_hint_info="Recite "Zbogom" starim vremenima.",
    no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
    no_data_hint_1="Želite ostati sretni? Samo trčite.",
    no_data_hint_2="Kardio vježba će vam omogućiti da se osjećate laganije i svježe svaki dan! ",
    no_data_hint_3="Normalna odrasla osoba troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
    not_binded_hint="Nijedan Mi Band nije povezan na ovaj račun, povežite jedan sada. ",
    new_record_info="Postigli ste novi rekord.",
    new_record_format="%d koraka, %s %d",
    today_goal_reached="Postigli ste svoj cilj za danas!",
    week_continue_reach_goal="Vi",
    challenge_format="Postigli ste svoj cilj %d dana za redom!",
    personal_best_format="Vaš najveći rekord je %d dana!",
    active_time_format_1="%dsati",
    active_time_format_2="%dsati %dmin",
    active_time_format_2="%dh %dmin",
    activie_run_format_1="Trčali ste %s. Ide vam fantastično!",
    activie_run_format_2="Trčali ste %s, Nevjerojatno ste izdržljivi!",
    activie_run_format_2="Trčali ste %s, Nevjerojatno!",
    activie_run_consumed="Potrošili ste %d kcal. %s",
    continue_with_skips_title="Niste postigli svoj cilj jučer. Nazovimo ga Dan ljenčarenja ;)",
    continue_with_skips_title_today="Niste postigli svoj cilj danas. Nazovimo ga Dan ljenčarenja ;)",
    personal_best_with_skips_format="Preostalo vam je %d Dana ljenčarenja ;)",
    continue_used_n_skips_format="Postigli ste svoj cilj %d dana za redom! You still have %d Lazy Days ;)",
    continue_used_0_skips_format="Postigli ste svoj cilj %d dana za redom! You have no Lazy Days left.",
    personal_best_on_skip_day_title="%d dan post. cilja! Zaslužili ste Dan ljenčarenja!",
    personal_best_on_skip_day_info="Nakon 7-dnevnog postizanja cilja za redom, zaslužili ste Dan ljenčarenja. To će pokriti propuštene ciljeve automatski.",
    manual_lazy_title="Niste postigli svoj cilj danas. Hoćete li ga nazvati Dan ljenčarenja?",
    manual_lazy_subtitle="The streak will cover up if you confirm.",
    manual_lazy_title_used="Danas je dan za ljenčarenje, uživajte!",
    manual_lazy_subtitle_used="The streak will be added one if you hit the goal later.",
    manual_fail_ytd_title = "Sorry, the streak broken yesterday.",
    manual_fail_ytd_subtitle = "Your streak until day before yesterday is %d.",

    get_distance_format=", ukupno od %d m.",
    activity_walk_format="%s Prohodano %d koraka %s",
    activity_walk_consumed_format="Potrošeno %d kal %s",
    activity_rope_skipping_format="%s jumped rope %d times",
    activity_situp_format="%s %d sit-ups",
    activity_consumed_format="Burned %dcal %s",
    activity_activity_format="%s Napravljeno %s %s",
    activity_activity_format_run="%s Worked out for %s, ran %s",
    last_night_sleeped_good_format="Prošle noći spavali ste %s. Sad ste stvarno naspavani!",
    last_night_sleeped_normal_format="Prošle noći spavali ste %s.",
    deep_sleep_format="Faza dubokog sna je bila %.",

    battery_low_info="Slaba baterija, stavite Mi Band na punjenje.",
    battery_very_low_info="Priključite na punjač",

    cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
    cannot_find_bracelet_info="Uvjerite se da vaš MiBand ima energije i nalazi se u blizini vašeg telefona.",
    challenge_to_get="%s dana od postizanja novog rekorda!",
    record_reach_max="Postigli ste svoj najveći novi rekord!",
    new_record_born="Novi rekord!",
 }
