-------------------------
-- Croatian Localization String resources
-- adria.mobiledevs.net (2014)
-- MASVA
-------------------------
localization_Croatian_table = {
    calories_table={
        {str="≈ Cucumber (100g)",   calories=14},
        {str="≈ Chicken broth (100g)",  calories=15},
        {str="≈ Cabbage (100g)",    calories=16},
        {str="≈ Pickled tomatoes (100g)",   calories=19},
        {str="≈ Mushrooms (100g)",  calories=20},
        {str="≈ Radishes (100g)",   calories=21},
        {str="≈ Eggplant (100g)",   calories=24},
        {str="≈ Pumpkin (100g)",    calories=25},
        {str="≈ Sauerkraut (100g)", calories=25},
        {str="≈ Mushroom soup (100g)",  calories=26},
        {str="≈ Broccoli (100g)",   calories=27},
        {str="≈ Vegetable soup (100g)", calories=28},
        {str="≈ Strawberries (100g)",   calories=30},
        {str="≈ Borsch (100g)", calories=36},
        {str="≈ Miso soup (100g)",  calories=36},
        {str="≈ Beetroot (100g)",   calories=36},
        {str="≈ Apple (100g)",  calories=37},
        {str="≈ Orange (100g)", calories=38},
        {str="≈ Potato soup (100g)",    calories=39},
        {str="≈ Watermelon (100g)", calories=39},
        {str="≈ Sorrel soup (100g)",    calories=40},
        {str="≈ Buttermilk 1% (100g)",  calories=40},
        {str="≈ Coca-Cola (100g)",  calories=42},
        {str="≈ 1.5% Milk (100g)",  calories=45},
        {str="≈ Red Bull (100g)",   calories=45},
        {str="≈ Chowder (100g)",    calories=46},
        {str="≈ Peach (100g)",  calories=46},
        {str="≈ Hochland cheese (25g)", calories=48},
        {str="≈ Cherry (100g)", calories=52},
        {str="≈ Orange juice (100g)",   calories=54},
        {str="≈ 3.2% milk (100g)",  calories=58},
        {str="≈ Ratatouille (100g)",    calories=60},
        {str="≈ Mashed potatoes (100g)",    calories=65},
        {str="≈ Pea soup (100g)",   calories=66},
        {str="≈ Mango (100g)",  calories=67},
        {str="≈ Lentil Soup (100g)",    calories=68},
        {str="≈ Strawberry jelly (100g)",   calories=69},
        {str="≈ Yogurt 1.5% (100g)",    calories=70},
        {str="≈ Crab sticks (100g)",    calories=73},
        {str="≈ Squid (100g)",  calories=75},
        {str="≈ Champagne (100g)",  calories=76},
        {str="≈ Wine 13% (100g)",   calories=78},
        {str="≈ Cabbage goulash (100g)",    calories=81},
        {str="≈ Boiled potatoes (100g)",    calories=82},
        {str="≈ Absinthe 60% ​​(100g)", calories=83},
        {str="≈ Milk mashed potatoes (100g)",   calories=85},
        {str="≈ Boiled egg (55g)",  calories=88},
        {str="≈ Banana (100g)", calories=89},
        {str="≈ Tomato beans (100g)",   calories=92},
        {str="≈ Ketchup (100g)",    calories=93},
        {str="≈ Rice with vegetables (100g)",   calories=94},
        {str="≈ Grain toast (1 slice)", calories=95},
        {str="≈ Tuna (100g)",   calories=96},
        {str="≈ Boiled walleye (100g)", calories=97},
        {str="≈ Vegetable stew (100g)", calories=99},
        {str="≈ Boiled carp (100g)",    calories=102},
        {str="≈ Fruit salad (100g)",    calories=103},
        {str="≈ Turkey fillet (100g)",  calories=104},
        {str="≈ Pork sturgeon (100g)",  calories=105},
        {str="≈ Rice (100g)",   calories=113},
        {str="≈ Zeppelins (100g)",  calories=117},
        {str="≈ Scrambled egg", calories=119},
        {str="≈ Squash paste (100g)",   calories=122},
        {str="≈ Japanese mayonnaise (100g)",    calories=134},
        {str="≈ Marshmallow (1pc)", calories=135},
        {str="≈ Cottage cheese (100g)", calories=136},
        {str="≈ Avocado roll",  calories=140},
        {str="≈ Cappuccino (100g)", calories=140},
        {str="≈ Lobio (100g)",  calories=141},
        {str="≈ Beef tongue (100g)",    calories=146},
        {str="≈ Beef goulash (100g)",   calories=148},
        {str="≈ Boiled chicken fillet (100g)",  calories=153},
        {str="≈ Fried potato (100g)",   calories=154},
        {str="≈ Pizza Margarita (100g)",    calories=157},
        {str="≈ Meatballs (100g)",  calories=159},
        {str="≈ Buckwheat (100g)",  calories=160},
        {str="≈ Rye bread (100g)",  calories=165},
        {str="≈ Roast turkey (100g)",   calories=165},
        {str="≈ Smoked chicken (100g)", calories=184},
        {str="≈ The cue pork (100g)",   calories=195},
        {str="≈ Sausages (100g)",   calories=198},
        {str="≈ Salmon (201g)", calories=201},
        {str="≈ Sour cream 20% (100g)", calories=204},
        {str="≈ Cream (100g)",  calories=206},
        {str="≈ Pasta Bolognese (100g)",    calories=208},
        {str="≈ Black bread (100g)",    calories=214},
        {str="≈ Candied fruits (100g)", calories=216},
        {str="≈ Salted herring (100g)", calories=217},
        {str="≈ Mushroom julienne (100g)",  calories=219},
        {str="≈ Caesar salad (100g)",   calories=221},
        {str="≈ Omelette (100g)",   calories=222},
        {str="≈ Light beer (0.5L)", calories=225},
        {str="≈ Oat bread (100g)",  calories=226},
        {str="≈ Lamb stew (100g)",  calories=226},
        {str="≈ Sundae (100g)", calories=227},
        {str="≈ McD Hamburger", calories=229},
        {str="≈ Roast pork (100g)", calories=233},
        {str="≈ White bread (100g)",    calories=235},
        {str="≈ Pita bread (100g)", calories=236},
        {str="≈ Vodka 40% (100g)",  calories=237},
        {str="≈ Basturma (100g)",   calories=240},
        {str="≈ Hamon (100g)",  calories=241},
        {str="≈ Ravioli (100g)",    calories=245},
        {str="≈ Red caviar (100g)", calories=249},
        {str="≈ Shawarma (100g)",   calories=250},
        {str="≈ Chicken sausages (100g)",   calories=259},
        {str="≈ Cutlets (100g)",    calories=260},
        {str="≈ Raisins (100g)",    calories=262},
        {str="≈ McD Cheeseburger",  calories=264},
        {str="≈ Milk sausages (100g)",  calories=270},
        {str="≈ Ham (100g)",    calories=270},
        {str="≈ Capelin smoked (100g)", calories=270},
        {str="≈ McD McNuggets (100g)",  calories=272},
        {str="≈ Dumplings (100g)",  calories=275},
        {str="≈ Grilled salmon (100g)", calories=283},
        {str="≈ Black Caviar (100g)",   calories=289},
        {str="≈ Mayonnaise (100g)", calories=299},
        {str="≈ Honey (100g)",  calories=302},
        {str="≈ McD Fries (100 g)", calories=303},
        {str="≈ Dates (100g)",  calories=306},
        {str="≈ Apple pancakes (100g)", calories=306},
        {str="≈ Stuffed cabbage (100g)",    calories=311},
        {str="≈ Pancakes (100g)",   calories=322},
        {str="≈ Omelet with cheese (100g)", calories=324},
        {str="≈ Liver sausages (100g)", calories=326},
        {str="≈ Donuts (100g)", calories=329},
        {str="≈ Cheesecake (100g)", calories=331},
        {str="≈ Pancakes with butter (100g)",   calories=332},
        {str="≈ Kebab (100g)",  calories=339},
        {str="≈ Spaghetti (100g)",  calories=344},
        {str="≈ Muffin (100g)", calories=345},
        {str="≈ Gingerbread (100g)",    calories=350},
        {str="≈ Beef stroganoff (100g)",    calories=355},
        {str="≈ Cornflakes (100g)", calories=363},
        {str="≈ Pasta (100g)",  calories=371},
        {str="≈ Steak (100g)",  calories=384},
        {str="≈ Crackers (100g)",   calories=386},
        {str="≈ Sugar (100g)",  calories=398},
        {str="≈ Oatmeal cookies (100g)",    calories=440},
        {str="≈ Schnitzel (100g)",  calories=456},
        {str="≈ Lasagne (100g)",    calories=460},
        {str="≈ Foie Gras (100g)",  calories=462},
        {str="≈ Honey cake (100g)", calories=478},
        {str="≈ Popcorn (100g)",    calories=480},
        {str="≈ Twix",  calories=483},
        {str="≈ Snickers",  calories=497},
        {str="≈ Bacon (100g)",  calories=500},
        {str="≈ McD Big Mac",   calories=510},
        {str="≈ Lays Max chips (100g)", calories=510},
        {str="≈ KitKat",    calories=524},
        {str="≈ Tiramisu (100g)",   calories=540},
        {str="≈ Pringles (100g)",   calories=540},
        {str="≈ Chocolate (100g)",  calories=546},
        {str="≈ Napoleon cake (100g)",  calories=552},
        {str="≈ Salami (100g)", calories=568},
        {str="≈ Roast goose (100g)",    calories=620},
        {str="≈ Fried dumplings (100g)",    calories=764},
        {str="≈ McD Big Tasty", calories=850},
    },

    ok='U redu',

    hour='sati',
    minute='min',
    month='mjesec',
    day='dan',
    step="koraka",
    km='km',
    minute_format='%dmin',
    hour_minute_format='%ds %dm',
    hour_format='%dsati',

    welcome_use="Dobrodošli...",
    last_week_walked_format='Prošli tjedan prohodali ste %d koraka.',
    last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
    last_month_walked_format='Prošli mjesec prohodali ste %d koraka.',
    last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',

    get_over_format=", oko %d grama ili masti.",
    click_to_get_help="Naučite više o Mi Bandu",
    take_a_walk="Prošetajte s vašim Mi Bandom",
    take_a_walk_info="Vaš band evidentira svaki vaš korak tijekom dana.",
    unlock_hint="Otključajte svoj telefon s MiBand!",
    unlock_hint_info="Otkrijte novi način zaštite vaše privatnosti.",
    no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
    no_data_hint_1="Ponavljanje je otac uspjeha.",
    no_data_hint_2="Težite napretku, a ne savršenstvu.",
    no_data_hint_3="Normalna odrasla osoba troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
    not_binded_hint="Nijedan Mi Band nije uparen s ovim računom, uparite ga sada. ",
    not_binded_hint_info="Također možete kliknuti na Vaga u izborniku.",
    new_record_info="Postigli ste novi rekord.",
    new_record_format="%d koraka, %s %d",
    today_goal_reached="Postigli ste svoj cilj za danas!",
    week_continue_reach_goal="Vi",

    challenge_format="Postigli ste svoj cilj %d dana za redom!",
    personal_best_format="Vaš najveći rekord je %d dana!",
    continue_with_skips_title="Niste postigli svoj cilj jučer. Nazovimo ga Dan ljenčarenja ;)",
    continue_with_skips_title_today="Niste postigli svoj cilj danas. Nazovimo ga Dan ljenčarenja ;)",
    personal_best_with_skips_format="Preostalo vam je %d Dana ljenčarenja ;)",
    continue_used_n_skips_format="Postigli ste svoj cilj %d dana za redom! Još imate %d Dan ljenčarenja ;)",
    continue_used_0_skips_format="Postigli ste svoj cilj %d dana za redom! Nemate više preostalih Dana ljenčarenja.",
    personal_best_on_skip_day_title="%d dan post. cilja! Zaslužili ste Dan ljenčarenja!",
    personal_best_on_skip_day_info="Nakon 7-dnevnog postizanja cilja za redom, zaslužili ste Dan ljenčarenja. To će pokriti propuštene ciljeve automatski.",
    manual_lazy_title="Niste postigli svoj cilj danas.",
    manual_lazy_subtitle="Vaš cilj će se nastaviti, ako ste označili danas kao Dan ljenčarenja.",
    manual_lazy_title_used="Danas je Dan ljenčarenja.",
    manual_lazy_subtitle_used="Možete zaraditi više Dana ljenčarenja obaranjem osobnih rekorda.",
    manual_fail_ytd_title = "Završili ste svoj niz jučer.",
    manual_fail_ytd_subtitle = "Postizanje niza je dugačak %d.",

    active_time_format_0="%dm",
    active_time_format_1="%ds",
    active_time_format_2="%ds %dm",
    activie_run_format_0="Trčali ste %s. Ide vam fantastično!",
    activie_run_format_1="Trčali ste %s, Nevjerojatno ste izdržljivi!",
    activie_run_format_2="Trčali ste %s, Nevjerojatno!",
    activie_run_consumed="Potrošili ste %dkcal. %s",

    get_distance_format="oko %dm.",
    activity_walk_format="%s Prohodano %d koraka %s",
    activity_walk_consumed_format="Potrošeno %dkal%s.",
    activity_rope_skipping_format="%s preskakanje užeta %d puta",
    activity_situp_format="%s %d trbušnjaka",
    activity_consumed_format="Potrošeno %dcal %s",
    activity_activity_format="%s Napravljeno %s %s",
    activity_activity_format_run="%s Vježbano %s, trčano %s",
    last_night_sleeped_good_format="Prošle noći spavali ste %s.",
    last_night_sleeped_normal_format="Prošle noći spavali ste %s.",
    deep_sleep_format="Faza dubokog sna je bila %.",

    battery_low_info="Stavite Mi Band na punjenje.",
    battery_very_low_info="Baterija banda je skoro prazna.",

    cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
    cannot_find_bracelet_info="Uvjerite se da j baterija vašeg MiBanda napunjena.",
    challenge_to_get="%s dana od postizanja novog rekorda!",
    record_reach_max="Izjednačili ste svoj postojeći rekord!",
    new_record_born="Postigli ste novi rekord!",

    minute='min',
    km='KM',
    minute_format='%d min',


    active_time_format_2="%dh %dmin",
    manual_lazy_subtitle="Niz će se prikriti ako potvrdite.",
    manual_lazy_subtitle_used="Niz će biti dodan ako postignete cilj poslije.",
    manual_fail_ytd_title = "Nažalost, niz je prekinut jučer",
    manual_fail_ytd_subtitle = "Vaš niz do jučer je bio %d.",
    ---------------Weight scale -------------------
    welcome_use_weight_scale = "Dobrodošli u korištenje vage",
    welcome_use_weight_scale_not_bind = "Koliknite da povežete vage",
    welcome_use_mi_health="Dobrodošli u korištenje MI health",

 }
